add cleanup job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -35,14 +35,15 @@ commands:
     steps:
       - run:
           name: Revert migrations
-          # Add when this will run
+          when: on_fail
           command: |
             SUCCESS=$(curl --insecure  https://kvdb.io/2mRbmYXyt9prv8MBeAmykd/migration_<< parameters.workflow_id >>)
             if(( $SUCCESS==1 ));
             then
               cd ~/project/backend
               npm install
-              npm run migration:revert
+              npm run build            
+              npm run migrations:revert
             fi
             
 jobs:
@@ -271,7 +272,6 @@ jobs:
               curl --insecure https://kvdb.io/2mRbmYXyt9prv8MBeAmykd/migration_$CIRCLE_WORKFLOW_ID -d '1'
             fi
       - destroy_environment
-#      - revert-migrations
 
   deploy-frontend:
     docker:
@@ -328,7 +328,7 @@ jobs:
             tar -czvf artifact-"$CIRCLE_WORKFLOW_ID".tar.gz dist
             aws s3 cp dist s3://udapeople-$CIRCLE_WORKFLOW_ID --recursive
       - destroy_environment
-#      - revert-migrations
+      - revert-migrations
 
   deploy-backend:
     docker:
@@ -397,7 +397,7 @@ jobs:
             - project/backend/.env
 
       - destroy_environment
-#      - revert-migrations
+      - revert-migrations
 
   smoke-test:
     docker:
@@ -435,12 +435,12 @@ jobs:
             echo ${URL} 
             if curl -s ${URL} | grep "Welcome"
             then
-              exit 0
+              exit 1
             else
               exit 1
             fi
       - destroy_environment
-#      - revert-migrations
+      - revert-migrations
 
 
   cloudfront-update:
@@ -467,26 +467,44 @@ jobs:
               --parameter-overrides WorkflowID="$CIRCLE_WORKFLOW_ID" \
               --stack-name InitialStack
       - destroy_environment
+      - revert-migrations
 
-#cleanup:
-#    docker:
-#      # Docker image here
-#    steps:
-#      # Checkout code from git
-#      - run:
-#          name: Get old stack workflow id
-#          command: |
-#            # your code here
-#            export OldWorkflowID="the id here"
-#            export STACKS=[] #put the list of stacks here
-#      - run:
-#          name: Remove old stacks and files
-#          command: |
-#            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-#            then
-#              # your code here
-#            fi
-#
+cleanup:
+    docker:
+      - image: cimg/node:13.8.0
+    steps:
+      - checkout
+      - install_awscli
+      - run:
+          name: Get old stack workflow id
+          command: |
+            # your code here
+            export OldWorkflowID="the id here"
+            export STACKS=[] #put the list of stacks here
+            export OldWorkflowID=$(aws cloudformation \
+                    list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                    --no-paginate --output text)
+            
+            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+                    --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
+
+            echo OldWorkflowID: "${OldWorkflowID}"
+            echo CIRCLE_WORKFLOW_ID "$CIRCLE_WORKFLOW_ID"
+            echo Stack names: "${STACKS[@]}"
+      - run:
+          name: Remove old stacks and files
+          command: |
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            then
+              echo "will delete:" ${OldWorkflowID}
+#              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+#              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+#              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+              echo "=======================Delete Confirmed========================"
+            fi
+            else
+              echo "Cannot Delete Stack Right Now"
+            fi
 
 workflows:
   default:
@@ -518,5 +536,5 @@ workflows:
           requires: [deploy-backend, deploy-frontend]
       - cloudfront-update:
           requires: [smoke-test]
-#      - cleanup:
-#          requires: [cloudfront-update]
+      - cleanup:
+          requires: [cloudfront-update]
